steps:
  # This step builds the container image.
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcp-hello-world', '.']

  # This step pushes the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/gcp-hello-world:$SHORT_SHA'
