spring:
  cloud:
    gcp:
      spanner:
        instance-id: gcp-demo-spanner-instance
        database: gcp-demo-db
      credentials:
        location: classpath:credential.json
      project-id: YOUR_PROJECT_ID
  datasource:
    initialization-mode: always
    continue-on-error: true
logging:
  level:
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
