spring:
  cloud:
    gcp:
      credentials:
        location: classpath:credential.json
      project-id: qwiklabs-gcp-02-713c582b3d0a
      spanner:
        instance-id: qwiklabs-gcp-02-713c582b3d0a
        database: gcp-demo
      bucketName: qwiklabs-gcp-02-713c582b3d0a
logging:
  level:
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: "shutdown"
  endpoint:
    shutdown:
      enabled: true
springdoc:
  show-actuator: true
