spring:
  cloud:
    gcp:
      credentials:
        location: classpath:credential.json
      project-id: ${PROJECT_ID}
      spanner:
        instance-id: ${SPANNER_INSTANCE_ID}
        database: ${SPANNER_DATABASE}
logging:
  level:
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
server:
  address: 0.0.0.0
