spring:
  cloud:
    gcp:
      credentials:
        location: classpath:credential.json
      project-id: qwiklabs-gcp-01-295376d7324a
      spanner:
        instance-id: qwiklabs-gcp-01-295376d7324a
        database: gcp-demo
logging:
  level:
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
server:
  address: 0.0.0.0
