spring:
  cloud:
    gcp:
      sql:
        database-name: gcp_demo
        instance-connection-name: qwiklabs-gcp-03-7197bd37f0a4:us-central1:qwiklabs-gcp-03-7197bd37f0a4
      credentials:
        location: classpath:credential.json
      project-id: qwiklabs-gcp-03-7197bd37f0a4
  datasource:
    username: [username]
    password: [password]
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
