apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-demo-app
  labels:
    app: gcp-demo-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp-demo-app
  template:
    metadata:
      labels:
        app: gcp-demo-app
    spec:
      containers:
        - name: gcp-demo-image
          image: gcr.io/YOUR_PROJECT_ID/gcp-demo-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: gcp-demo-app
spec:
  selector:
    app: gcp-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
